
export const Data = [
  //Kushas
  { id: 1, name: "ALOO 65", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 2, name: "Gobi Manchurian", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 3, name: "Gobi 65", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 4, name: "Chilli Gobi", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 5, name: "Paneer Butter Masala", price: 220, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 6, name: "Chicken Biryani", price: 250, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 7, name: "Veg Biryani", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 8, name: "Mutton Curry", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 9, name: "Dal Tadka", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 10, name: "Fish Fry", price: 230, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 11, name: "Veg Fried Rice", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 12, name: "Egg Curry", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 13, name: "Masala Dosa", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 14, name: "Chicken 65", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 15, name: "Veg Pulao", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 16, name: "Prawn Curry", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 17, name: "Chole Bhature", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 18, name: "Chicken Curry", price: 240, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 19, name: "Rajma Chawal", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 20, name: "Mutton Biryani", price: 300, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 21, name: "Palak Paneer", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 22, name: "Tandoori Chicken", price: 270, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 23, name: "Veg Hakka Noodles", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 24, name: "Mutton Rogan Josh", price: 320, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 25, name: "Aloo Paratha", price: 100, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 26, name: "Fish Curry", price: 240, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 27, name: "Veg Cutlet", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 28, name: "Egg Biryani", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 29, name: "Bhindi Masala", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 30, name: "Chicken Tikka Masala", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 31, name: "Paneer Tikka", price: 220, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 32, name: "Butter Chicken", price: 270, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 33, name: "Veg Kofta Curry", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 34, name: "Mutton Keema", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 35, name: "Veg Spring Roll", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 36, name: "Chicken Shawarma", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 37, name: "Paneer Bhurji", price: 190, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 38, name: "Fish Biryani", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 39, name: "Veg Kurma", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 40, name: "Egg Fried Rice", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 41, name: "Paneer Pakora", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 42, name: "Chicken Pakora", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 43, name: "Veg Momos", price: 140, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 44, name: "Chicken Momos", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 45, name: "Paneer Manchurian", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 46, name: "Mutton Korma", price: 290, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 47, name: "Veg Sandwich", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 48, name: "Chicken Sandwich", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 49, name: "Veg Burger", price: 130, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 50, name: "Chicken Burger", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 51, name: "Paneer Pizza", price: 250, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 52, name: "Chicken Pizza", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 53, name: "Veg Wrap", price: 140, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 54, name: "Chicken Wrap", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 55, name: "Paneer Frankie", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 56, name: "Egg Frankie", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 57, name: "Veg Soup", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 58, name: "Chicken Soup", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 59, name: "Paneer Roll", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 60, name: "Mutton Roll", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 61, name: "Veg Thali", price: 250, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 62, name: "Non-Veg Thali", price: 300, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 63, name: "Paneer Masala Dosa", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 64, name: "Chicken Dosa", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 65, name: "Veg Uttapam", price: 140, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 66, name: "Egg Uttapam", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 67, name: "Paneer Kulcha", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 68, name: "Keema Kulcha", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 69, name: "Veg Pani Puri", price: 100, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 70, name: "Chicken Pani Puri", price: 130, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 71, name: "Paneer Pulao", price: 190, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 72, name: "Chicken Pulao", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 73, name: "Veg Kebab", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 74, name: "Chicken Kebab", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 75, name: "Paneer Biryani", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 76, name: "Mutton Biryani Special", price: 320, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 77, name: "Veg Chowmein", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 78, name: "Chicken Chowmein", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 79, name: "Paneer Cutlet", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 80, name: "Fish Cutlet", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 81, name: "Veg Manchow Soup", price: 130, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 82, name: "Chicken Manchow Soup", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 83, name: "Paneer Chilli", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 84, name: "Chicken Chilli", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 85, name: "Veg Kurkure Momos", price: 140, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 86, name: "Chicken Kurkure Momos", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 87, name: "Paneer Bhatura", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 88, name: "Keema Bhatura", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 89, name: "Veg Idli", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 90, name: "Chicken Idli", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 91, name: "Paneer Masala", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 92, name: "Chicken Masala", price: 240, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 93, name: "Veg Stew", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 94, name: "Mutton Stew", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 95, name: "Paneer Curry", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 96, name: "Fish Curry Special", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 97, name: "Veg Masala Rice", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 98, name: "Egg Masala Rice", price: 190, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 99, name: "Paneer Pulusu", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 100, name: "Chicken Pulusu", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  //KNL
  { id: 101, name: "ALOO 65", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 102, name: "Gobi Manchurian", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 103, name: "Gobi 65", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 104, name: "Chilli Gobi", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 105, name: "Paneer Butter Masala", price: 220, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 106, name: "Chicken Biryani", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 107, name: "Veg Biryani", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 108, name: "Mutton Curry", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 109, name: "Dal Tadka", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 110, name: "Fish Fry", price: 230, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 111, name: "Veg Fried Rice", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 112, name: "Egg Curry", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 113, name: "Masala Dosa", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 114, name: "Chicken 65", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 115, name: "Veg Pulao", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 116, name: "Prawn Curry", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 117, name: "Chole Bhature", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 118, name: "Chicken Curry", price: 240, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 119, name: "Rajma Chawal", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 120, name: "Mutton Biryani", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 121, name: "Palak Paneer", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 122, name: "Tandoori Chicken", price: 270, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 123, name: "Veg Hakka Noodles", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 124, name: "Mutton Rogan Josh", price: 320, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 125, name: "Aloo Paratha", price: 100, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 126, name: "Paneer Tikka", price: 220, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 127, name: "Butter Chicken", price: 270, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 128, name: "Veg Kofta Curry", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 129, name: "Mutton Keema", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 130, name: "Veg Spring Roll", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 131, name: "Chicken Shawarma", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 132, name: "Paneer Bhurji", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 133, name: "Fish Biryani", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 134, name: "Veg Kurma", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 135, name: "Egg Fried Rice", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 136, name: "Paneer Pakora", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 137, name: "Chicken Pakora", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 138, name: "Veg Momos", price: 140, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 139, name: "Chicken Momos", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 140, name: "Paneer Manchurian", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 141, name: "Mutton Korma", price: 290, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 142, name: "Veg Sandwich", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 143, name: "Chicken Sandwich", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 144, name: "Veg Burger", price: 130, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 145, name: "Chicken Burger", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 146, name: "Paneer Pizza", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 147, name: "Chicken Pizza", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 148, name: "Veg Wrap", price: 140, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 149, name: "Chicken Wrap", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 150, name: "Paneer Frankie", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  // KNL
  { id: 151, name: "Egg Frankie", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 152, name: "Veg Soup", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 153, name: "Chicken Soup", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 154, name: "Paneer Roll", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 155, name: "Mutton Roll", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 156, name: "Veg Thali", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 157, name: "Non-Veg Thali", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 158, name: "Paneer Masala Dosa", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 159, name: "Chicken Dosa", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 160, name: "Veg Uttapam", price: 140, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 161, name: "Egg Uttapam", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 162, name: "Paneer Kulcha", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 163, name: "Keema Kulcha", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 164, name: "Veg Pani Puri", price: 100, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 165, name: "Chicken Pani Puri", price: 130, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 166, name: "Paneer Pulao", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 167, name: "Chicken Pulao", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 168, name: "Veg Kebab", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 169, name: "Chicken Kebab", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 170, name: "Paneer Biryani", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 171, name: "Mutton Biryani Special", price: 320, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 172, name: "Veg Chowmein", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 173, name: "Chicken Chowmein", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 174, name: "Paneer Cutlet", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 175, name: "Fish Cutlet", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 176, name: "Veg Manchow Soup", price: 130, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 177, name: "Chicken Manchow Soup", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 178, name: "Paneer Chilli", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 179, name: "Chicken Chilli", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 180, name: "Veg Kurkure Momos", price: 140, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 181, name: "Chicken Kurkure Momos", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 182, name: "Paneer Bhatura", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 183, name: "Keema Bhatura", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 184, name: "Veg Idli", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 185, name: "Chicken Idli", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 186, name: "Paneer Masala", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 187, name: "Chicken Masala", price: 240, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 188, name: "Veg Stew", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 189, name: "Mutton Stew", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 190, name: "Paneer Curry", price: 200, restid: 2, button: "Add",type: "veg", symbol: "🟢", image: "2.jpg" },
  
  { id: 191, name: "Fish Curry Special", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 192, name: "Veg Masala Rice", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 193, name: "Egg Masala Rice", price: 190, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 194, name: "Paneer Pulusu", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 195, name: "Chicken Pulusu", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 196, name: "Veg Kurma Special", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 197, name: "Mutton Kurma Special", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 198, name: "Paneer Bhaji", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 199, name: "Chicken Bhaji", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 200, name: "Veg Pulav Special", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 201, name: "Fish Pulav Special", price: 240, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 202, name: "Paneer Masala Fry", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 203, name: "Chicken Masala Fry", price: 230, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 204, name: "Veg Special Curry", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 205, name: "Mutton Special Curry", price: 310, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  //snow field
  { id: 206, name: "Veg Cheese Pizza", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 207, name: "Veg Corn Pizza", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 208, name: "Veg Burger", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 209, name: "Garlic Bread", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 210, name: "Paneer Butter Masala", price: 220, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 211, name: "Chicken Biryani", price: 250, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 212, name: "Veg Biryani", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 213, name: "Mutton Curry", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 214, name: "Dal Tadka", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 215, name: "Fish Fry", price: 230, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 216, name: "Veg Fried Rice", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 217, name: "Egg Curry", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 218, name: "Masala Dosa", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 219, name: "Chicken 65", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 220, name: "Veg Pulao", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 221, name: "Prawn Curry", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 222, name: "Chole Bhature", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 223, name: "Chicken Curry", price: 240, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 224, name: "Rajma Chawal", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 225, name: "Mutton Biryani", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 226, name: "Palak Paneer", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 227, name: "Tandoori Chicken", price: 270, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 228, name: "Veg Hakka Noodles", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 229, name: "Mutton Rogan Josh", price: 320, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 230, name: "Aloo Paratha", price: 100, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 231, name: "Paneer Tikka", price: 220, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 232, name: "Butter Chicken", price: 270, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 233, name: "Veg Kofta Curry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 234, name: "Mutton Keema", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 235, name: "Veg Spring Roll", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 236, name: "Chicken Shawarma", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 237, name: "Paneer Bhurji", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 238, name: "Fish Biryani", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 239, name: "Veg Kurma", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 240, name: "Egg Fried Rice", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 241, name: "Paneer Pakora", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 242, name: "Chicken Pakora", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 243, name: "Veg Momos", price: 140, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 244, name: "Chicken Momos", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 245, name: "Paneer Manchurian", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 246, name: "Mutton Korma", price: 290, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 247, name: "Veg Sandwich", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 248, name: "Chicken Sandwich", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 249, name: "Veg Burger", price: 130, restid: 3, button: "Add", type: "veg", symbol: "🟢", image:"2.jpg" },
  // KNL
  { id: 250, name: "Chicken Burger", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 251, name: "Paneer Pizza", price: 250, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 252, name: "Chicken Pizza", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 253, name: "Veg Wrap", price: 140, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 254, name: "Chicken Wrap", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 255, name: "Paneer Frankie", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 256, name: "Egg Frankie", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 257, name: "Veg Soup", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 258, name: "Chicken Soup", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 259, name: "Paneer Roll", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 260, name: "Mutton Roll", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 261, name: "Veg Thali", price: 250, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 262, name: "Non-Veg Thali", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 263, name: "Paneer Masala Dosa", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 264, name: "Chicken Dosa", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 265, name: "Veg Uttapam", price: 140, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 266, name: "Egg Uttapam", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 267, name: "Paneer Kulcha", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 268, name: "Keema Kulcha", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 269, name: "Veg Pani Puri", price: 100, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 270, name: "Chicken Pani Puri", price: 130, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 271, name: "Paneer Pulao", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 272, name: "Chicken Pulao", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 273, name: "Veg Kebab", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 274, name: "Chicken Kebab", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 275, name: "Paneer Biryani", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 276, name: "Mutton Biryani Special", price: 320, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 277, name: "Veg Chowmein", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 278, name: "Chicken Chowmein", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 279, name: "Paneer Cutlet", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 280, name: "Fish Cutlet", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 281, name: "Veg Manchow Soup", price: 130, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 282, name: "Chicken Manchow Soup", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 283, name: "Paneer Chilli", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 284, name: "Chicken Chilli", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 285, name: "Veg Kurkure Momos", price: 140, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 286, name: "Chicken Kurkure Momos", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 287, name: "Paneer Bhatura", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 288, name: "Keema Bhatura", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 289, name: "Veg Idli", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🔺", image: "2.jpg" },
  { id: 290, name: "Chicken Idli", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 291, name: "Paneer Masala", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 292, name: "Chicken Masala", price: 240, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 293, name: "Veg Stew", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 294, name: "Mutton Stew", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 295, name: "Paneer Curry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 296, name: "Fish Curry Special", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 297, name: "Veg Masala Rice", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 298, name: "Egg Masala Rice", price: 190, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 299, name: "Paneer Pulusu", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },

  { id: 300, name: "Chicken Pulusu", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 301, name: "Veg Kurma Special", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 302, name: "Mutton Kurma Special", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 303, name: "Paneer Bhaji", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 304, name: "Chicken Bhaji", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 305, name: "Veg Pulav Special", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 306, name: "Fish Pulav Special", price: 240, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 307, name: "Paneer Masala Fry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 308, name: "Chicken Masala Fry", price: 230, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 309, name: "Veg Special Curry", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 310, name: "Mutton Special Curry", price: 310, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  //Mayuri
  { id: 311, name: "Veg Cheese Pizza", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 312, name: "Veg Corn Pizza", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 313, name: "Veg Burger", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 314, name: "Garlic Bread", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  
  { id: 315, name: "Paneer Butter Masala", price: 220, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 316, name: "Chicken Biryani", price: 250, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 317, name: "Veg Biryani", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 318, name: "Mutton Curry", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 319, name: "Dal Tadka", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 320, name: "Fish Fry", price: 230, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 321, name: "Veg Fried Rice", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 322, name: "Egg Curry", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 323, name: "Masala Dosa", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 324, name: "Chicken 65", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 325, name: "Veg Pulao", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 326, name: "Prawn Curry", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 327, name: "Chole Bhature", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 328, name: "Chicken Curry", price: 240, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 329, name: "Rajma Chawal", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 330, name: "Mutton Biryani", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 331, name: "Palak Paneer", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 332, name: "Tandoori Chicken", price: 270, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 333, name: "Veg Hakka Noodles", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 334, name: "Mutton Rogan Josh", price: 320, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 335, name: "Aloo Paratha", price: 100, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 336, name: "Paneer Tikka", price: 220, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 337, name: "Butter Chicken", price: 270, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 338, name: "Veg Kofta Curry", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 339, name: "Mutton Keema", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 340, name: "Veg Spring Roll", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 341, name: "Chicken Shawarma", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 342, name: "Paneer Bhurji", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 343, name: "Fish Biryani", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 344, name: "Veg Kurma", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 345, name: "Egg Fried Rice", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 346, name: "Paneer Pakora", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 347, name: "Chicken Pakora", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 348, name: "Veg Momos", price: 140, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 349, name: "Chicken Momos", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 350, name: "Paneer Manchurian", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 351, name: "Mutton Korma", price: 290, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 352, name: "Veg Sandwich", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 353, name: "Chicken Sandwich", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 354, name: "Veg Burger", price: 130, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 355, name: "Chicken Burger", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 356, name: "Paneer Pizza", price: 250, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 357, name: "Chicken Pizza", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 358, name: "Veg Wrap", price: 140, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 359, name: "Chicken Wrap", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 360, name: "Paneer Frankie", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 361, name: "Egg Frankie", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 362, name: "Veg Soup", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 363, name: "Chicken Soup", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 364, name: "Paneer Roll", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 365, name: "Mutton Roll", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 366, name: "Veg Thali", price: 250, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 367, name: "Non-Veg Thali", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 368, name: "Paneer Masala Dosa", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 369, name: "Chicken Dosa", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 370, name: "Veg Uttapam", price: 140, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 371, name: "Egg Uttapam", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 372, name: "Paneer Kulcha", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 373, name: "Keema Kulcha", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 374, name: "Veg Pani Puri", price: 100, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 375, name: "Chicken Pani Puri", price: 130, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 376, name: "Paneer Pulao", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 377, name: "Chicken Pulao", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 378, name: "Veg Kebab", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 379, name: "Chicken Kebab", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 380, name: "Paneer Biryani", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 381, name: "Mutton Biryani Special", price: 320, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 382, name: "Veg Chowmein", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 383, name: "Chicken Chowmein", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 384, name: "Paneer Cutlet", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 385, name: "Fish Cutlet", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 386, name: "Veg Manchow Soup", price: 130, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 387, name: "Chicken Manchow Soup", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 388, name: "Paneer Chilli", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 389, name: "Chicken Chilli", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 390, name: "Veg Kurkure Momos", price: 140, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 391, name: "Chicken Kurkure Momos", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 392, name: "Paneer Bhatura", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 393, name: "Keema Bhatura", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 394, name: "Veg Idli", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 395, name: "Chicken Idli", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 396, name: "Paneer Masala", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 397, name: "Chicken Masala", price: 240, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 398, name: "Veg Stew", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 399, name: "Mutton Stew", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 400, name: "Paneer Curry", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 401, name: "Fish Curry Special", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 402, name: "Veg Masala Rice", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 403, name: "Egg Masala Rice", price: 190, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 404, name: "Paneer Pulusu", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 405, name: "Chicken Pulusu", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 406, name: "Veg Kurma Special", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 407, name: "Mutton Kurma Special", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 408, name: "Paneer Bhaji", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 409, name: "Chicken Bhaji", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 410, name: "Veg Pulav Special", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 411, name: "Fish Pulav Special", price: 240, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  //Th bro
  { id: 412, name: "Veg biryani", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 413, name: "Non-Veg biryani", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 414, name: "Veg Fried Rice", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 415, name: "Non-Veg Fried Rice", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
{ id: 416, name: "Paneer Butter Masala", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 417, name: "Chicken Curry", price: 240, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 418, name: "Veg Pulao", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 419, name: "Mutton Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 420, name: "Dal Tadka", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 421, name: "Fish Fry", price: 230, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 422, name: "Chole Bhature", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 423, name: "Egg Curry", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 424, name: "Rajma Chawal", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 425, name: "Prawn Curry", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 426, name: "Palak Paneer", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 427, name: "Tandoori Chicken", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 428, name: "Veg Hakka Noodles", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 429, name: "Mutton Rogan Josh", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 430, name: "Aloo Paratha", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 431, name: "Paneer Tikka", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 432, name: "Butter Chicken", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 433, name: "Veg Kofta Curry", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 434, name: "Mutton Keema", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 435, name: "Veg Spring Roll", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 436, name: "Chicken Shawarma", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 437, name: "Paneer Bhurji", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 438, name: "Fish Biryani", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 439, name: "Veg Kurma", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 440, name: "Egg Fried Rice", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 441, name: "Paneer Pakora", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 442, name: "Chicken Pakora", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 443, name: "Veg Momos", price: 140, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 444, name: "Chicken Momos", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 445, name: "Paneer Manchurian", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 446, name: "Mutton Korma", price: 290, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 447, name: "Veg Sandwich", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 448, name: "Chicken Sandwich", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 449, name: "Veg Burger", price: 130, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 450, name: "Chicken Burger", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 451, name: "Paneer Pizza", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 452, name: "Chicken Pizza", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 453, name: "Veg Wrap", price: 140, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 454, name: "Chicken Wrap", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 455, name: "Paneer Frankie", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image:"2.jpg" },
  { id: 456, name: "Egg Frankie", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 457, name: "Veg Soup", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 458, name: "Chicken Soup", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 459, name: "Paneer Roll", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 460, name: "Mutton Roll", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 461, name: "Veg Thali", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 462, name: "Non-Veg Thali", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 463, name: "Paneer Masala Dosa", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 464, name: "Chicken Dosa", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 465, name: "Veg Uttapam", price: 140, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 466, name: "Egg Uttapam", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 467, name: "Paneer Kulcha", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 468, name: "Keema Kulcha", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 469, name: "Veg Pani Puri", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 470, name: "Chicken Pani Puri", price: 130, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 471, name: "Paneer Pulao", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 472, name: "Chicken Pulao", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 473, name: "Veg Kebab", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 474, name: "Chicken Kebab", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 475, name: "Paneer Biryani", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 476, name: "Mutton Biryani Special", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 477, name: "Veg Chowmein", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 478, name: "Chicken Chowmein", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 479, name: "Paneer Cutlet", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 480, name: "Fish Cutlet", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },

  { id: 481, name: "Veg Manchow Soup", price: 130, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 482, name: "Chicken Manchow Soup", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 483, name: "Paneer Chilli", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 484, name: "Chicken Chilli", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 485, name: "Veg Kurkure Momos", price: 140, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 486, name: "Chicken Kurkure Momos", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 487, name: "Paneer Bhatura", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 488, name: "Keema Bhatura", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 489, name: "Veg Idli", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 490, name: "Chicken Idli", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
{ id: 491, name: "Paneer Masala", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 492, name: "Chicken Masala", price: 240, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 493, name: "Veg Stew", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 494, name: "Mutton Stew", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 495, name: "Paneer Curry", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 496, name: "Fish Curry Special", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 497, name: "Veg Masala Rice", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 498, name: "Egg Masala Rice", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 499, name: "Paneer Pulusu", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 500, name: "Chicken Pulusu", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 501, name: "Veg Kurma Special", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 502, name: "Mutton Kurma Special", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 503, name: "Paneer Bhaji", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 504, name: "Chicken Bhaji", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 505, name: "Veg Pulav Special", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 506, name: "Fish Pulav Special", price: 240, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 507, name: "Paneer Masala Fry", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 508, name: "Chicken Masala Fry", price: 230, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 509, name: "Veg Special Curry", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 510, name: "Mutton Special Curry", price: 310, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 511, name: "Paneer Tandoori", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 512, name: "Chicken Tandoori", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },



  //Sai
  { id: 513, name: "Veg biryani", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 514, name: "Non-Veg biryani", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 515, name: "Veg Fried Rice", price: 170, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 516, name: "Non-Veg Fried Rice", price: 170, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
   { id: 517, name: "Paneer Butter Masala", price: 220, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 518, name: "Chicken Curry", price: 240, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 519, name: "Veg Pulao", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 520, name: "Mutton Biryani", price: 300, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 521, name: "Dal Tadka", price: 150, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 522, name: "Fish Fry", price: 230, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 523, name: "Chole Bhature", price: 150, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 524, name: "Egg Curry", price: 180, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 525, name: "Rajma Chawal", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 526, name: "Prawn Curry", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 527, name: "Palak Paneer", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 528, name: "Tandoori Chicken", price: 270, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 529, name: "Veg Hakka Noodles", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 530, name: "Mutton Rogan Josh", price: 320, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 531, name: "Aloo Paratha", price: 100, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 532, name: "Paneer Tikka", price: 220, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 533, name: "Butter Chicken", price: 270, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 534, name: "Veg Kofta Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 535, name: "Mutton Keema", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 536, name: "Veg Spring Roll", price: 150, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 537, name: "Chicken Shawarma", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 538, name: "Paneer Bhurji", price: 190, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 539, name: "Fish Biryani", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 540, name: "Veg Kurma", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 541, name: "Egg Fried Rice", price: 170, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 542, name: "Paneer Pakora", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 543, name: "Chicken Pakora", price: 180, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 544, name: "Veg Momos", price: 140, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 545, name: "Chicken Momos", price: 160, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 546, name: "Paneer Manchurian", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 547, name: "Mutton Korma", price: 290, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 548, name: "Veg Sandwich", price: 120, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 549, name: "Chicken Sandwich", price: 150, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 550, name: "Veg Burger", price: 130, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 551, name: "Chicken Burger", price: 160, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 552, name: "Paneer Pizza", price: 250, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 553, name: "Chicken Pizza", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 554, name: "Veg Wrap", price: 140, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 555, name: "Chicken Wrap", price: 170, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 556, name: "Chicken Wrap", price: 170, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 557, name: "Paneer Frankie", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 558, name: "Egg Frankie", price: 150, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 559, name: "Veg Soup", price: 120, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 560, name: "Chicken Soup", price: 150, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 561, name: "Paneer Roll", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 562, name: "Mutton Roll", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 563, name: "Veg Thali", price: 250, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 564, name: "Non-Veg Thali", price: 300, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 565, name: "Paneer Masala Dosa", price: 150, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 566, name: "Chicken Dosa", price: 180, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 567, name: "Veg Uttapam", price: 140, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 568, name: "Egg Uttapam", price: 160, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 569, name: "Paneer Kulcha", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 570, name: "Keema Kulcha", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 571, name: "Veg Pani Puri", price: 100, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 572, name: "Chicken Pani Puri", price: 130, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 573, name: "Paneer Pulao", price: 190, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 574, name: "Chicken Pulao", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 575, name: "Veg Kebab", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 576, name: "Chicken Kebab", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 577, name: "Paneer Biryani", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 578, name: "Mutton Biryani Special", price: 320, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 579, name: "Veg Chowmein", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 580, name: "Chicken Chowmein", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 581, name: "Paneer Cutlet", price: 150, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 582, name: "Fish Cutlet", price: 180, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 583, name: "Veg Manchow Soup", price: 130, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 584, name: "Chicken Manchow Soup", price: 150, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 585, name: "Paneer Chilli", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 586, name: "Chicken Chilli", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 587, name: "Veg Kurkure Momos", price: 140, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 588, name: "Chicken Kurkure Momos", price: 160, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 589, name: "Paneer Bhatura", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 590, name: "Keema Bhatura", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 591, name: "Veg Idli", price: 120, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 592, name: "Chicken Idli", price: 150, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 593, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 594, name: "Chicken Masala", price: 240, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
{ id: 595, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 596, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 597, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 598, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 599, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 600, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 601, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 602, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 603, name: "Veg Kurma Special", price: 190, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 604, name: "Mutton Kurma Special", price: 300, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 605, name: "Paneer Bhaji", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 606, name: "Chicken Bhaji", price: 200, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 607, name: "Veg Pulav Special", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 608, name: "Fish Pulav Special", price: 240, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 609, name: "Paneer Masala Fry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 610, name: "Chicken Masala Fry", price: 230, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 611, name: "Veg Special Curry", price: 190, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 612, name: "Mutton Special Curry", price: 310, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 613, name: "Paneer Tandoori", price: 220, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },


//pv
  { id: 614, name: "Veg Cheese Pizza", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 615, name: "Veg Corn Pizza", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 616, name: "Veg Burger", price: 170, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 617, name: "Garlic Bread", price: 170, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
 { id: 618, name: "Paneer Butter Masala", price: 220, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 619, name: "Chicken Curry", price: 240, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 620, name: "Veg Pulao", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 621, name: "Mutton Biryani", price: 300, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 622, name: "Dal Tadka", price: 150, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 623, name: "Fish Fry", price: 230, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 624, name: "Chole Bhature", price: 150, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 625, name: "Egg Curry", price: 180, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 626, name: "Rajma Chawal", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 627, name: "Prawn Curry", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 628, name: "Palak Paneer", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 629, name: "Tandoori Chicken", price: 270, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 630, name: "Veg Hakka Noodles", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 631, name: "Mutton Rogan Josh", price: 320, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 632, name: "Aloo Paratha", price: 100, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 633, name: "Paneer Tikka", price: 220, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 634, name: "Butter Chicken", price: 270, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 635, name: "Veg Kofta Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 636, name: "Mutton Keema", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 637, name: "Veg Spring Roll", price: 150, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 638, name: "Chicken Shawarma", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 639, name: "Paneer Bhurji", price: 190, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 640, name: "Fish Biryani", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 641, name: "Veg Kurma", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 642, name: "Egg Fried Rice", price: 170, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 643, name: "Paneer Pakora", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 644, name: "Chicken Pakora", price: 180, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 645, name: "Veg Momos", price: 140, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 646, name: "Chicken Momos", price: 160, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 647, name: "Paneer Manchurian", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 648, name: "Mutton Korma", price: 290, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 649, name: "Veg Sandwich", price: 120, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 650, name: "Chicken Sandwich", price: 150, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 651, name: "Veg Burger", price: 130, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 652, name: "Chicken Burger", price: 160, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 653, name: "Paneer Pizza", price: 250, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 654, name: "Chicken Pizza", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 655, name: "Veg Wrap", price: 140, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 656, name: "Chicken Wrap", price: 170, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 657, name: "Paneer Frankie", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 658, name: "Egg Frankie", price: 150, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 659, name: "Veg Soup", price: 120, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 660, name: "Chicken Soup", price: 150, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 661, name: "Paneer Roll", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 662, name: "Mutton Roll", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 663, name: "Veg Thali", price: 250, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 664, name: "Non-Veg Thali", price: 300, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 665, name: "Paneer Masala Dosa", price: 150, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 666, name: "Chicken Dosa", price: 180, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 667, name: "Veg Uttapam", price: 140, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 668, name: "Egg Uttapam", price: 160, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 669, name: "Paneer Kulcha", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 670, name: "Keema Kulcha", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 671, name: "Veg Pani Puri", price: 100, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 672, name: "Chicken Pani Puri", price: 130, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 673, name: "Paneer Pulao", price: 190, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 674, name: "Chicken Pulao", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 675, name: "Veg Kebab", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 676, name: "Chicken Kebab", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 677, name: "Paneer Biryani", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 678, name: "Mutton Biryani Special", price: 320, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 679, name: "Veg Chowmein", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 680, name: "Chicken Chowmein", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 681, name: "Paneer Cutlet", price: 150, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 682, name: "Fish Cutlet", price: 180, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 683, name: "Veg Manchow Soup", price: 130, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 684, name: "Chicken Manchow Soup", price: 150, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 685, name: "Paneer Chilli", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 686, name: "Chicken Chilli", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 687, name: "Veg Kurkure Momos", price: 140, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 688, name: "Chicken Kurkure Momos", price: 160, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
 { id: 689, name: "Paneer Bhatura", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 690, name: "Keema Bhatura", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 691, name: "Veg Idli", price: 120, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 692, name: "Chicken Idli", price: 150, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 693, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 694, name: "Chicken Masala", price: 240, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 695, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 696, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
   { id: 697, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 698, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 699, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 700, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 701, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 702, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 703, name: "Veg Kurma Special", price: 190, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 704, name: "Mutton Kurma Special", price: 300, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 705, name: "Paneer Bhaji", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 706, name: "Chicken Bhaji", price: 200, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 707, name: "Veg Pulav Special", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 708, name: "Fish Pulav Special", price: 240, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 709, name: "Paneer Masala Fry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 710, name: "Chicken Masala Fry", price: 230, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 711, name: "Veg Special Curry", price: 190, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 712, name: "Mutton Special Curry", price: 310, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 713, name: "Paneer Tandoori", price: 220, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
  { id: 714, name: "Chicken Tandoori", price: 270, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "2.jpg" },
  { id: 715, name: "Veg Deluxe Thali", price: 280, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "2.jpg" },
];
